<?php
// INFO GENERALE
define('CHAR_DATA_OFFSET_GUILD_ID',151);
define('CHAR_DATA_OFFSET_GUILD_RANK',152);
define('CHAR_DATA_OFFSET_ARENA_TEAM_ID_2v2',1634);
define('CHAR_DATA_OFFSET_ARENA_TEAM_ID_3v3',1640);
define('CHAR_DATA_OFFSET_ARENA_TEAM_ID_5v5',1642);
define('CHAR_DATA_OFFSET_GOLD',1546);
define('CHAR_DATA_OFFSET_HONOR_KILL',1602);
define('CHAR_DATA_OFFSET_HONOR_POINTS',1648);
define('CHAR_DATA_OFFSET_ARENA_POINTS',1649);

// INFO PERSONNAGE
define('CHAR_DATA_OFFSET_HEALTH',23);
define('CHAR_DATA_OFFSET_SEX',22);
define('CHAR_DATA_OFFSET_MANA',24);
define('CHAR_DATA_OFFSET_RAGE',27);
define('CHAR_DATA_OFFSET_ENER',27);
define('CHAR_DATA_OFFSET_RUNI',27);
define('CHAR_DATA_OFFSET_HEALTH_MAX',31);
define('CHAR_DATA_OFFSET_MANA_MAX',32);
define('CHAR_DATA_OFFSET_RAGE_MAX',35);
define('CHAR_DATA_OFFSET_ENER_MAX',35);
define('CHAR_DATA_OFFSET_RUNI_MAX',35);
define('CHAR_DATA_OFFSET_LEVEL',53);
define('CHAR_DATA_OFFSET_BASEATTACKTIME',61);
define('CHAR_DATA_OFFSET_OFFHANDATTACKTIME',62);
define('CHAR_DATA_OFFSET_RANGEDATTACKTIME',63);
define('CHAR_DATA_OFFSET_MINDAMAGE',69);
define('CHAR_DATA_OFFSET_MAXDAMAGE',70);
define('CHAR_DATA_OFFSET_MINOFFHANDDAMAGE',71);
define('CHAR_DATA_OFFSET_MAXOFFHANDDAMAGE',72);
define('CHAR_DATA_OFFSET_STR',84);
define('CHAR_DATA_OFFSET_AGI',85);
define('CHAR_DATA_OFFSET_STA',86);
define('CHAR_DATA_OFFSET_INT',87);
define('CHAR_DATA_OFFSET_SPI',88);
define('CHAR_DATA_OFFSET_ARMOR',99);
define('CHAR_DATA_OFFSET_RES_HOLY',100);
define('CHAR_DATA_OFFSET_RES_FIRE',101);
define('CHAR_DATA_OFFSET_RES_NATURE',102);
define('CHAR_DATA_OFFSET_RES_FROST',103);
define('CHAR_DATA_OFFSET_RES_SHADOW',104);
define('CHAR_DATA_OFFSET_RES_ARCANE',105);
define('CHAR_DATA_OFFSET_AP',123);
define('CHAR_DATA_OFFSET_AP_BON',124);
define('CHAR_DATA_OFFSET_RANGED_AP',126);
define('CHAR_DATA_OFFSET_RANGED_AP_BON',127);
define('CHAR_DATA_OFFSET_MINRANGEDDAMAGE',129);
define('CHAR_DATA_OFFSET_MAXRANGEDDAMAGE',130);
define('CHAR_DATA_OFFSET_EQU_HEAD',260);
define('CHAR_DATA_OFFSET_EQU_NECK',278);
define('CHAR_DATA_OFFSET_EQU_SHOULDER',296);
define('CHAR_DATA_OFFSET_EQU_SHIRT',314);
define('CHAR_DATA_OFFSET_EQU_CHEST',332);
define('CHAR_DATA_OFFSET_EQU_BELT',350);
define('CHAR_DATA_OFFSET_EQU_LEGS',368);
define('CHAR_DATA_OFFSET_EQU_FEET',386);
define('CHAR_DATA_OFFSET_EQU_WRIST',404);
define('CHAR_DATA_OFFSET_EQU_GLOVES',422);
define('CHAR_DATA_OFFSET_EQU_FINGER1',440);
define('CHAR_DATA_OFFSET_EQU_FINGER2',458);
define('CHAR_DATA_OFFSET_EQU_TRINKET1',476);
define('CHAR_DATA_OFFSET_EQU_TRINKET2',494);
define('CHAR_DATA_OFFSET_EQU_BACK',512);
define('CHAR_DATA_OFFSET_EQU_MAIN_HAND',530);
define('CHAR_DATA_OFFSET_EQU_OFF_HAND',548);
define('CHAR_DATA_OFFSET_EQU_RANGED',566);
define('CHAR_DATA_OFFSET_EQU_TABARD',584);
define('CHAR_DATA_OFFSET_EQU_PROJECT',1572);
define('CHAR_DATA_OFFSET_EXP',1010);
define('CHAR_DATA_OFFSET_EXP_TOTAL',1011);
define('CHAR_DATA_OFFSET_SKILL_DATA',1012);
define('CHAR_DATA_OFFSET_BLOCK',1400);
define('CHAR_DATA_OFFSET_DODGE',1401);
define('CHAR_DATA_OFFSET_PARRY',1402);
define('CHAR_DATA_OFFSET_EXPER',1403);
define('CHAR_DATA_OFFSET_RANGE_CRIT',1404);
define('CHAR_DATA_OFFSET_CRIT',1405);
define('CHAR_DATA_OFFSET_SPELL_CRIT_PER',1406);
define('CHAR_DATA_OFFSET_CRIT_SORT',1410);
define('CHAR_DATA_OFFSET_BONU_DEGA',1549);
//define('CHAR_DATA_OFFSET_REGEN_MANA',1564);
define('CHAR_DATA_OFFSET_REGEN_MANA',1018);
define('CHAR_DATA_OFFSET_BONU_SOINS',1568);
//define('CHAR_DATA_OFFSET_DEF',1606);
define('CHAR_DATA_OFFSET_TOUCHE_MEL',1610);
define('CHAR_DATA_OFFSET_TOUCHE_DIST',1611);
define('CHAR_DATA_OFFSET_TOUCHE_SORT',1612);
define('CHAR_DATA_OFFSET_RESIL',1619);

$data = explode(' ',$donnees['data']);

// INFO GENERALE
$CHAR_DATA_OFFSET_GUILD_ID = $data[CHAR_DATA_OFFSET_GUILD_ID];
$CHAR_DATA_OFFSET_GUILD_RANK = $data[CHAR_DATA_OFFSET_GUILD_RANK];
$CHAR_DATA_OFFSET_ARENA_TEAM_ID_2v2 = $data[CHAR_DATA_OFFSET_ARENA_TEAM_ID_2v2];
$CHAR_DATA_OFFSET_ARENA_TEAM_ID_3v3 = $data[CHAR_DATA_OFFSET_ARENA_TEAM_ID_3v3];
$CHAR_DATA_OFFSET_ARENA_TEAM_ID_5v5 = $data[CHAR_DATA_OFFSET_ARENA_TEAM_ID_5v5];
$CHAR_DATA_OFFSET_GOLD = $data[CHAR_DATA_OFFSET_GOLD];
$CHAR_DATA_OFFSET_HONOR_KILL = $data[CHAR_DATA_OFFSET_HONOR_KILL];
$CHAR_DATA_OFFSET_HONOR_POINTS = $data[CHAR_DATA_OFFSET_HONOR_POINTS];
$CHAR_DATA_OFFSET_ARENA_POINTS = $data[CHAR_DATA_OFFSET_ARENA_POINTS];

$rang = $data[CHAR_DATA_OFFSET_GUILD_RANK];
$mort = $data[CHAR_DATA_OFFSET_HONOR_KILL];
$arene = $data[CHAR_DATA_OFFSET_ARENA_POINTS];
$guild = $data[CHAR_DATA_OFFSET_GUILD_ID];

// INFO PERSONNAGE
$CHAR_DATA_OFFSET_HEALTH = $data[CHAR_DATA_OFFSET_HEALTH]; // Vie actuel
$CHAR_DATA_OFFSET_SEX = $data[CHAR_DATA_OFFSET_SEX];
$CHAR_DATA_OFFSET_MANA = $data[CHAR_DATA_OFFSET_MANA];
$CHAR_DATA_OFFSET_RAGE = $data[CHAR_DATA_OFFSET_RAGE];
$CHAR_DATA_OFFSET_ENER = $data[CHAR_DATA_OFFSET_ENER];
$CHAR_DATA_OFFSET_RUNI = $data[CHAR_DATA_OFFSET_RUNI];
$CHAR_DATA_OFFSET_HEALTH_MAX = $data[CHAR_DATA_OFFSET_HEALTH_MAX]; // Vie Maximal
$CHAR_DATA_OFFSET_MANA_MAX = $data[CHAR_DATA_OFFSET_MANA_MAX];
$CHAR_DATA_OFFSET_RAGE_MAX = $data[CHAR_DATA_OFFSET_RAGE_MAX];
$CHAR_DATA_OFFSET_ENER_MAX = $data[CHAR_DATA_OFFSET_ENER_MAX];
$CHAR_DATA_OFFSET_RUNI_MAX = $data[CHAR_DATA_OFFSET_RUNI_MAX];
$CHAR_DATA_OFFSET_LEVEL = $data[CHAR_DATA_OFFSET_LEVEL];
$CHAR_DATA_OFFSET_BASEATTACKTIME = $data[CHAR_DATA_OFFSET_BASEATTACKTIME];
$CHAR_DATA_OFFSET_OFFHANDATTACKTIME = $data[CHAR_DATA_OFFSET_OFFHANDATTACKTIME];
$CHAR_DATA_OFFSET_RANGEDATTACKTIME = $data[CHAR_DATA_OFFSET_RANGEDATTACKTIME];
$CHAR_DATA_OFFSET_MINDAMAGE = $data[CHAR_DATA_OFFSET_MINDAMAGE];
$CHAR_DATA_OFFSET_MAXDAMAGE = $data[CHAR_DATA_OFFSET_MAXDAMAGE];
$CHAR_DATA_OFFSET_MINOFFHANDDAMAGE = $data[CHAR_DATA_OFFSET_MINOFFHANDDAMAGE];
$CHAR_DATA_OFFSET_MAXOFFHANDDAMAGE = $data[CHAR_DATA_OFFSET_MAXOFFHANDDAMAGE];
$CHAR_DATA_OFFSET_STR = $data[CHAR_DATA_OFFSET_STR];
$CHAR_DATA_OFFSET_AGI = $data[CHAR_DATA_OFFSET_AGI];
$CHAR_DATA_OFFSET_STA = $data[CHAR_DATA_OFFSET_STA];
$CHAR_DATA_OFFSET_INT = $data[CHAR_DATA_OFFSET_INT];
$CHAR_DATA_OFFSET_SPI = $data[CHAR_DATA_OFFSET_INT];
$CHAR_DATA_OFFSET_ARMOR = $data[CHAR_DATA_OFFSET_ARMOR];
$CHAR_DATA_OFFSET_RES_HOLY = $data[CHAR_DATA_OFFSET_RES_HOLY];
$CHAR_DATA_OFFSET_RES_FIRE = $data[CHAR_DATA_OFFSET_RES_FIRE];
$CHAR_DATA_OFFSET_RES_NATURE = $data[CHAR_DATA_OFFSET_RES_NATURE];
$CHAR_DATA_OFFSET_RES_FROST = $data[CHAR_DATA_OFFSET_RES_FROST];
$CHAR_DATA_OFFSET_RES_SHADOW = $data[CHAR_DATA_OFFSET_RES_SHADOW];
$CHAR_DATA_OFFSET_RES_ARCANE = $data[CHAR_DATA_OFFSET_RES_ARCANE];
$CHAR_DATA_OFFSET_AP = $data[CHAR_DATA_OFFSET_AP];
$CHAR_DATA_OFFSET_AP_BON = $data[CHAR_DATA_OFFSET_AP_BON];
$CHAR_DATA_OFFSET_AP_TOTAL = $data[CHAR_DATA_OFFSET_AP] + $data[CHAR_DATA_OFFSET_AP_BON];
$CHAR_DATA_OFFSET_RANGED_AP = $data[CHAR_DATA_OFFSET_RANGED_AP];
$CHAR_DATA_OFFSET_RANGED_AP_BON = $data[CHAR_DATA_OFFSET_RANGED_AP_BON];
$CHAR_DATA_OFFSET_RANGED_AP_TOTAL = CHAR_DATA_OFFSET_RANGED_AP + CHAR_DATA_OFFSET_RANGED_AP_BON;
$CHAR_DATA_OFFSET_MINRANGEDDAMAGE = $data[CHAR_DATA_OFFSET_MINRANGEDDAMAGE];
$CHAR_DATA_OFFSET_MAXRANGEDDAMAGE = $data[CHAR_DATA_OFFSET_MAXRANGEDDAMAGE];
$CHAR_DATA_OFFSET_EXP = $data[CHAR_DATA_OFFSET_EXP];
$CHAR_DATA_OFFSET_EXP_TOTAL = $data[CHAR_DATA_OFFSET_EXP_TOTAL];
$CHAR_DATA_OFFSET_SKILL_DATA = $data[CHAR_DATA_OFFSET_SKILL_DATA];
$CHAR_DATA_OFFSET_BLOCK = $data[CHAR_DATA_OFFSET_BLOCK];
$CHAR_DATA_OFFSET_DODGE = $data[CHAR_DATA_OFFSET_DODGE];
$CHAR_DATA_OFFSET_PARRY = $data[CHAR_DATA_OFFSET_PARRY];
$CHAR_DATA_OFFSET_EXPER = $data[CHAR_DATA_OFFSET_EXPER];
$CHAR_DATA_OFFSET_RANGE_CRIT = $data[CHAR_DATA_OFFSET_RANGE_CRIT];
$CHAR_DATA_OFFSET_CRIT = $data[CHAR_DATA_OFFSET_CRIT];
//$CHAR_DATA_OFFSET_OFFHAND_CRIT = $data[1405];
$CHAR_DATA_OFFSET_SPELL_CRIT_PER = $data[CHAR_DATA_OFFSET_SPELL_CRIT_PER];
$CHAR_DATA_OFFSET_CRIT_SORT = $data[CHAR_DATA_OFFSET_CRIT_SORT];
$CHAR_DATA_OFFSET_TOUCHE_MEL = $data[CHAR_DATA_OFFSET_TOUCHE_MEL];
$CHAR_DATA_OFFSET_TOUCHE_DIST = $data[CHAR_DATA_OFFSET_TOUCHE_DIST];
$CHAR_DATA_OFFSET_TOUCHE_SORT = $data[CHAR_DATA_OFFSET_TOUCHE_SORT];
$CHAR_DATA_OFFSET_RESIL = $data[CHAR_DATA_OFFSET_RESIL];
$CHAR_DATA_OFFSET_REGEN_MANA = $data[CHAR_DATA_OFFSET_REGEN_MANA];
$CHAR_DATA_OFFSET_BONU_DEGA = $data[CHAR_DATA_OFFSET_BONU_DEGA];
$CHAR_DATA_OFFSET_BONU_SOINS = $data[CHAR_DATA_OFFSET_BONU_SOINS];
$CHAR_DATA_OFFSET_DEF = $data[CHAR_DATA_OFFSET_DEF];


//EQUIPPEMENT PERSONNAGE
$CHAR_DATA_EQU_HEAD = $data[CHAR_DATA_OFFSET_EQU_HEAD];
$CHAR_DATA_EQU_NECK = $data[CHAR_DATA_OFFSET_EQU_NECK];
$CHAR_DATA_EQU_SHOULDER = $data[CHAR_DATA_OFFSET_EQU_SHOULDER];
$CHAR_DATA_EQU_SHIRT = $data[CHAR_DATA_OFFSET_EQU_SHIRT];
$CHAR_DATA_EQU_CHEST = $data[CHAR_DATA_OFFSET_EQU_CHEST];
$CHAR_DATA_EQU_BELT = $data[CHAR_DATA_OFFSET_EQU_BELT];
$CHAR_DATA_EQU_LEGS = $data[CHAR_DATA_OFFSET_EQU_LEGS];
$CHAR_DATA_EQU_FEET = $data[CHAR_DATA_OFFSET_EQU_FEET];
$CHAR_DATA_EQU_WRIST = $data[CHAR_DATA_OFFSET_EQU_WRIST];
$CHAR_DATA_EQU_GLOVES = $data[CHAR_DATA_OFFSET_EQU_GLOVES];
$CHAR_DATA_EQU_FINGER1 = $data[CHAR_DATA_OFFSET_EQU_FINGER1];
$CHAR_DATA_EQU_FINGER2 = $data[CHAR_DATA_OFFSET_EQU_FINGER2];
$CHAR_DATA_EQU_TRINKET1 = $data[CHAR_DATA_OFFSET_EQU_TRINKET1];
$CHAR_DATA_EQU_TRINKET2 = $data[CHAR_DATA_OFFSET_EQU_TRINKET2];
$CHAR_DATA_EQU_BACK = $data[CHAR_DATA_OFFSET_EQU_BACK];
$CHAR_DATA_EQU_MAIN_HAND = $data[CHAR_DATA_OFFSET_EQU_MAIN_HAND];
$CHAR_DATA_EQU_OFF_HAND = $data[CHAR_DATA_OFFSET_EQU_OFF_HAND];
$CHAR_DATA_EQU_RANGED = $data[CHAR_DATA_OFFSET_EQU_RANGED];
$CHAR_DATA_EQU_TABARD = $data[CHAR_DATA_OFFSET_EQU_TABARD];
$CHAR_DATA_EQU_PROJECT = $data[CHAR_DATA_OFFSET_EQU_PROJECT];



$sex = dechex($data[CHAR_DATA_OFFSET_SEX]);
$sex = str_pad($sex,8, 0, STR_PAD_LEFT);
$sex = $sex{3};
?>